# Generated by Django 2.0.4 on 2018-05-17 06:37

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionName', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='OptionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionGroupName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('productSKU', models.CharField(max_length=100)),
                ('productName', models.CharField(max_length=120)),
                ('productPrice', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('productWeight', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('productCartDesc', models.CharField(max_length=120)),
                ('productShortDesc', models.CharField(max_length=250)),
                ('productLongDesc', models.TextField()),
                ('productThumb', models.FileField(blank=True, null=True, upload_to=products.models.upload_image_path)),
                ('productImage1', models.FileField(blank=True, null=True, upload_to=products.models.upload_image_path)),
                ('productImage2', models.FileField(blank=True, null=True, upload_to=products.models.upload_image_path)),
                ('productImage3', models.FileField(blank=True, null=True, upload_to=products.models.upload_image_path)),
                ('productUpdateDate', models.DateTimeField(auto_now=True)),
                ('productTimestamp', models.DateTimeField(auto_now_add=True)),
                ('productStock', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('productLive', models.BooleanField(default=False)),
                ('ProducyLimited', models.BooleanField(default=False)),
                ('ProductLocation', models.CharField(max_length=250)),
                ('featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('productCategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
            ],
        ),
        migrations.CreateModel(
            name='productOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionPriceIncrement', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('optionGroupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_for_option', to='products.OptionGroup')),
                ('optionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_for_product', to='products.Option')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_for_option', to='products.Product')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='optionGroupId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.OptionGroup'),
        ),
    ]
