# Generated by Django 2.0.4 on 2018-05-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180518_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productCartDesc',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='productLongDesc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='productSKU',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='productShortDesc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
