# Generated by Django 2.0.4 on 2018-05-18 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180518_0038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-productTimestamp', '-productUpdateDate']},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='ProducyLimited',
            new_name='ProductLimited',
        ),
    ]
