# Generated by Django 2.0.4 on 2018-05-21 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20180518_0140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-productTimestamp']},
        ),
    ]
