# Generated by Django 2.0.4 on 2018-05-21 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20180521_0039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-productTimestamp', '-productUpdateDate']},
        ),
    ]
